// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace RestaurantInfrastructure.Migrations
{
    [DbContext(typeof(DbRestaurantContext))]
    partial class DbRestaurantContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RestDomain.Models.Bonuse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset?>("DataGranted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("integer")
                        .HasColumnName("EmployeeID");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("integer")
                        .HasColumnName("ManagerID");

                    b.Property<string>("Reason")
                        .HasColumnType("character varying");

                    b.HasKey("Id")
                        .HasName("Bonuses_pkey");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ManagerId");

                    b.ToTable("Bonuses");
                });

            modelBuilder.Entity("RestDomain.Models.Employer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("CreatedAt")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .HasColumnType("character varying");

                    b.Property<string>("LastName")
                        .HasColumnType("character varying");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("SalaryPerHour")
                        .HasColumnType("numeric");

                    b.HasKey("Id")
                        .HasName("Employers_pkey");

                    b.ToTable("Employers");
                });

            modelBuilder.Entity("RestDomain.Models.Instructor", b =>
                {
                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer")
                        .HasColumnName("EmployeeID");

                    b.Property<int?>("ExperienceYears")
                        .HasColumnType("integer");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("integer")
                        .HasColumnName("ManagerID");

                    b.Property<string>("Specialization")
                        .HasColumnType("character varying");

                    b.HasKey("EmployeeId")
                        .HasName("Instructor_pkey");

                    b.HasIndex("ManagerId");

                    b.ToTable("Instructor");
                });

            modelBuilder.Entity("RestDomain.Models.Manager", b =>
                {
                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer")
                        .HasColumnName("EmployeeID");

                    b.Property<string>("Departmet")
                        .HasColumnType("character varying");

                    b.Property<int?>("OfficePhone")
                        .HasColumnType("integer");

                    b.HasKey("EmployeeId")
                        .HasName("Managers_pkey");

                    b.ToTable("Managers");
                });

            modelBuilder.Entity("RestDomain.Models.Shift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("integer")
                        .HasColumnName("EmployeeID");

                    b.Property<TimeSpan?>("EndTime")
                        .HasColumnType("time");

                    b.Property<DateOnly?>("ShiftDate")
                        .HasColumnType("date");

                    b.Property<int?>("ShiftTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("ShiftTypeID");

                    b.Property<TimeSpan?>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id")
                        .HasName("Shifts_pkey");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ShiftTypeId");

                    b.ToTable("Shifts");
                });

            modelBuilder.Entity("RestDomain.Models.ShiftsType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("character varying");

                    b.HasKey("Id")
                        .HasName("ShiftsTypes_pkey");

                    b.ToTable("ShiftsTypes");
                });

            modelBuilder.Entity("RestDomain.Models.TrainingProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("InstuctorD")
                        .HasColumnType("integer");

                    b.Property<int?>("KnowledgeLevel")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("ReviewDate")
                        .HasColumnType("date");

                    b.Property<string>("Station")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("WorkerId")
                        .HasColumnType("integer")
                        .HasColumnName("WorkerID");

                    b.HasKey("Id")
                        .HasName("TrainingProgress_pkey");

                    b.HasIndex("InstuctorD");

                    b.HasIndex("WorkerId");

                    b.ToTable("TrainingProgress");
                });

            modelBuilder.Entity("RestDomain.Models.Worker", b =>
                {
                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer")
                        .HasColumnName("EmployeeID");

                    b.Property<int?>("InstructorId")
                        .HasColumnType("integer")
                        .HasColumnName("InstructorID");

                    b.Property<int?>("IsCertified")
                        .HasColumnType("integer");

                    b.Property<bool?>("IsMinor")
                        .HasColumnType("boolean");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("integer")
                        .HasColumnName("ManagerID");

                    b.HasKey("EmployeeId")
                        .HasName("Workers_pkey");

                    b.HasIndex("InstructorId");

                    b.HasIndex("ManagerId");

                    b.ToTable("Workers");
                });

            modelBuilder.Entity("RestDomain.Models.Bonuse", b =>
                {
                    b.HasOne("RestDomain.Models.Employer", "Employee")
                        .WithMany("Bonuses")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("Bonuses_EmployeeID_fkey");

                    b.HasOne("RestDomain.Models.Manager", "Manager")
                        .WithMany("Bonuses")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("Bonuses_ManagerID_fkey");

                    b.Navigation("Employee");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("RestDomain.Models.Instructor", b =>
                {
                    b.HasOne("RestDomain.Models.Employer", "Employee")
                        .WithOne("Instructor")
                        .HasForeignKey("RestDomain.Models.Instructor", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Instructor_EmployeeID_fkey");

                    b.HasOne("RestDomain.Models.Manager", "Manager")
                        .WithMany("Instructors")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("Instructor_ManagerID_fkey");

                    b.Navigation("Employee");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("RestDomain.Models.Manager", b =>
                {
                    b.HasOne("RestDomain.Models.Employer", "Employee")
                        .WithOne("Manager")
                        .HasForeignKey("RestDomain.Models.Manager", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Managers_EmloyeeID_fkey");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("RestDomain.Models.Shift", b =>
                {
                    b.HasOne("RestDomain.Models.Employer", "Employee")
                        .WithMany("Shifts")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("Shifts_EmpoyeeID_fkey");

                    b.HasOne("RestDomain.Models.ShiftsType", "ShiftType")
                        .WithMany("Shifts")
                        .HasForeignKey("ShiftTypeId")
                        .HasConstraintName("Shifts_ShiftTypeID_fkey");

                    b.Navigation("Employee");

                    b.Navigation("ShiftType");
                });

            modelBuilder.Entity("RestDomain.Models.TrainingProgress", b =>
                {
                    b.HasOne("RestDomain.Models.Instructor", "InstuctorDNavigation")
                        .WithMany("TrainingProgresses")
                        .HasForeignKey("InstuctorD")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("TrainingProgress_InstuctorD_fkey");

                    b.HasOne("RestDomain.Models.Worker", "Worker")
                        .WithMany("TrainingProgresses")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("TrainingProgress_WorkerID_fkey");

                    b.Navigation("InstuctorDNavigation");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("RestDomain.Models.Worker", b =>
                {
                    b.HasOne("RestDomain.Models.Employer", "Employee")
                        .WithOne("Worker")
                        .HasForeignKey("RestDomain.Models.Worker", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Workers_EmpoyeeID_fkey");

                    b.HasOne("RestDomain.Models.Instructor", "Instructor")
                        .WithMany("Workers")
                        .HasForeignKey("InstructorId")
                        .HasConstraintName("Workers_InstructorID_fkey");

                    b.HasOne("RestDomain.Models.Manager", "Manager")
                        .WithMany("Workers")
                        .HasForeignKey("ManagerId")
                        .HasConstraintName("Workers_ManagerID_fkey");

                    b.Navigation("Employee");

                    b.Navigation("Instructor");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("RestDomain.Models.Employer", b =>
                {
                    b.Navigation("Bonuses");

                    b.Navigation("Instructor");

                    b.Navigation("Manager");

                    b.Navigation("Shifts");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("RestDomain.Models.Instructor", b =>
                {
                    b.Navigation("TrainingProgresses");

                    b.Navigation("Workers");
                });

            modelBuilder.Entity("RestDomain.Models.Manager", b =>
                {
                    b.Navigation("Bonuses");

                    b.Navigation("Instructors");

                    b.Navigation("Workers");
                });

            modelBuilder.Entity("RestDomain.Models.ShiftsType", b =>
                {
                    b.Navigation("Shifts");
                });

            modelBuilder.Entity("RestDomain.Models.Worker", b =>
                {
                    b.Navigation("TrainingProgresses");
                });
#pragma warning restore 612, 618
        }
    }
}
